name: "Draft new release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true
      startFromMain:
        description: "Start release from main branch? (Mainly for production hotfix)"
        type: boolean
        required: true
        default: false

jobs:
  draft-new-release:
    name: "Draft a new release (always chose main branch)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY_PRIVATE }}
      - name: Reset develop branch branch
        if: ${{ !(github.event.inputs.startFromMain == 'true') }}
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: Get next version
        id: next-version
        run: |
          npm --no-git-tag-version version ${{ github.event.inputs.release_type }}
          echo "::set-output name=version::$(grep '"version":' package.json | cut -d\" -f4)"

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Extract branch name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: release/v${{ steps.next-version.outputs.version }}
          commit-message: Prepare release ${{ steps.next-version.outputs.version }}
          title: Release version ${{ steps.next-version.outputs.version }}
          delete-branch: false
          reviewers: ${{ github.actor }} # By default, we request a review from the person who triggered the workflow.
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
